_wandb:
    value:
        cli_version: 0.21.0
        e:
            34cpr21pd9j4e1avbsgk4tpma64f0nap:
                codePath: train_masked_blocks.py
                codePathLocal: train_masked_blocks.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "48891670528"
                        used: "29794746368"
                email: jen@lexikat.com
                executable: /home/cc/.pyenv/versions/3.10.12/bin/python3
                git:
                    commit: 0e4f5b649d328d7b59f255762a304fae27a1aecf
                    remote: https://github.com/Lexikat-Pte-Ltd/liouvilleViT.git
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-547dcd75-d1b0-9dde-ec20-390ddb431a13
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-edab6a47-dfd2-8209-9941-77cb0b4dacc6
                host: cc-System-Product-Name
                memory:
                    total: "134969368576"
                os: Linux-6.8.0-64-generic-x86_64-with-glibc2.35
                program: /media/cc/2T/liouvilleViT/train_masked_blocks.py
                python: CPython 3.10.12
                root: /media/cc/2T/liouvilleViT
                startedAt: "2025-07-20T15:34:47.558717Z"
                writerId: 34cpr21pd9j4e1avbsgk4tpma64f0nap
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
            "4": 3.10.12
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
batch_size:
    value: 1
epochs:
    value: 100
learning_rate:
    value: 0.0002
num_blocks_per_grid:
    value: 10000
